// lib/notifications.ts
// v24 M2 item 5 — real notification data access
//
// Notifications are generated by Postgres triggers (see migration 006).
// This module handles the read path (list, counts) and the write path
// (markRead, markAllRead). The UI never writes notification content —
// only the database layer does that.

import { createClient } from '@/lib/supabase'

export type NotifType =
  | 'waiver_signed'
  | 'exception_flagged'
  | 'legal_hold'
  | 'carrier_notified'
  | 'group_complete'
  | 'overage_warning'
  | 'pass_recognized'

export type NotifPriority = 'high' | 'normal' | 'low'

export interface NotificationRecord {
  id:          string
  type:        NotifType
  priority:    NotifPriority
  title:       string
  body:        string
  link:        string | null
  linkLabel:   string | null
  read:        boolean
  waiverId:    string | null
  incidentId:  string | null
  createdAt:   string
}

// ── Read ──────────────────────────────────────────────────────────────────────

export async function listNotifications(
  limit = 50
): Promise<NotificationRecord[]> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('notifications')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(limit)

  if (error) {
    console.error('[notifications] listNotifications:', error.message)
    return []
  }
  return (data ?? []).map(mapRow)
}

// ── Write ─────────────────────────────────────────────────────────────────────

export async function markRead(notificationId: string): Promise<void> {
  const supabase = createClient()
  const { error } = await supabase
    .from('notifications')
    .update({ read: true })
    .eq('id', notificationId)
    .eq('read', false)   // no-op if already read — avoids unnecessary writes

  if (error) console.error('[notifications] markRead:', error.message)
}

export async function markAllRead(): Promise<void> {
  const supabase = createClient()
  const { error } = await supabase
    .from('notifications')
    .update({ read: true })
    .eq('read', false)

  if (error) console.error('[notifications] markAllRead:', error.message)
}

// ── Mapper ────────────────────────────────────────────────────────────────────

function mapRow(row: Record<string, unknown>): NotificationRecord {
  return {
    id:         row.id as string,
    type:       row.type as NotifType,
    priority:   row.priority as NotifPriority,
    title:      row.title as string,
    body:       row.body as string,
    link:       row.link as string | null,
    linkLabel:  row.link_label as string | null,
    read:       row.read as boolean,
    waiverId:   row.waiver_id as string | null,
    incidentId: row.incident_id as string | null,
    createdAt:  row.created_at as string,
  }
}
