// lib/openapi.ts
// The OpenAPI 3.1 contract for the Liabl public API v1. This object IS the
// spec: it is served verbatim at GET /api/v1/openapi and rendered at
// /developers. Keeping it in the repo (not generated at runtime) makes the
// contract reviewable in diffs and version-controlled alongside the routes
// it describes. When an endpoint changes, update it here in the same PR.
//
// Client-safe (a plain data object, no imports) so either a route handler
// or a page can serve it.

export const OPENAPI_SPEC = {
  openapi: '3.1.0',
  info: {
    title: 'Liabl API',
    version: '1.0.0',
    description: [
      'The Liabl API lets booking engines and third-party developers create',
      'bookings, track waiver signature status, and receive real-time webhooks —',
      'all scoped to a single operator.',
      '',
      '## Authentication',
      '',
      'Every request authenticates with an **API key** as a bearer token:',
      '',
      '```',
      'Authorization: Bearer liabl_live_xxxxxxxxxxxxxxxxxxxxxxxx',
      '```',
      '',
      'Create keys in the operator console under **Developers**. A key belongs',
      'to exactly one operator, and the operator is derived **from the key** —',
      'never from the request body or path. A key can only ever read or write',
      "its own operator's data. Keys are shown once at creation and stored only",
      'as a hash; if you lose one, revoke it and create another.',
      '',
      '## Scopes',
      '',
      'Keys are least-privilege. Each endpoint declares the scope it needs:',
      '',
      '- `reservations:read` — read reservations and signature status',
      '- `reservations:write` — create reservations and add attendees',
      '- `waivers:read` — read waiver status and sealed PDFs',
      '- `webhooks:manage` — manage webhook endpoints',
      '',
      'A request whose key lacks the required scope returns `403 insufficient_scope`.',
      '',
      '## Modes: live and test',
      '',
      'Keys are prefixed `liabl_live_` or `liabl_test_`. Every response carries',
      'an `X-Liabl-Mode` header echoing which mode served it. Test keys currently',
      'operate against the same data as live keys (isolated sandbox data is on the',
      'roadmap) — use them to build and label integration traffic distinctly.',
      '',
      '## Rate limits',
      '',
      'Requests are limited to **120 per minute per key**. Every response includes',
      '`X-RateLimit-Limit` and `X-RateLimit-Remaining`; a `429 rate_limited`',
      'response includes `Retry-After` (seconds). Back off and retry.',
      '',
      '## Errors',
      '',
      'Errors use a consistent envelope:',
      '',
      '```json',
      '{ "error": { "code": "not_found", "message": "Reservation not found." } }',
      '```',
      '',
      '## Webhooks',
      '',
      'Instead of polling, subscribe an HTTPS endpoint (console → Developers →',
      'Webhooks, or `POST /webhooks`) to events. Liabl POSTs a JSON payload the',
      'moment each happens:',
      '',
      '- `waiver.signed` — a waiver is signed and its sealed PDF is ready (the',
      '  headline signal)',
      '- `document.signed` — a supplemental document is signed',
      '- `reservation.member_signed` — an attendee completed their check-in',
      '- `reservation.completed` — every attendee in a reservation has signed',
      '',
      'Each delivery carries a signature header so you can verify it came from',
      'Liabl and was not tampered with:',
      '',
      '```',
      'X-Liabl-Signature: t=1785400000,v1=<hmac_sha256_hex>',
      '```',
      '',
      'The signature is `HMAC_SHA256(endpoint_secret, "{t}.{raw_request_body}")`.',
      'Verify it before trusting a payload (Node example):',
      '',
      '```js',
      'import crypto from "crypto";',
      '',
      'function verifyLiablSignature(secret, header, rawBody) {',
      '  const parts = Object.fromEntries(header.split(",").map(p => p.split("=")));',
      '  const expected = crypto.createHmac("sha256", secret)',
      '    .update(`${parts.t}.${rawBody}`).digest("hex");',
      '  return crypto.timingSafeEqual(Buffer.from(parts.v1), Buffer.from(expected));',
      '}',
      '```',
      '',
      'Reject deliveries whose timestamp `t` is far from now to prevent replays.',
      'Deliveries retry with exponential backoff (~1m, 5m, 30m, 2h, 6h) and carry',
      'a stable `id` — dedupe on it, since an event may be delivered more than once.',
    ].join('\n'),
    contact: { name: 'Liabl', url: 'https://api.liabl.ai/developers' },
  },
  servers: [
    { url: 'https://api.liabl.ai/api/v1', description: 'Production' },
  ],
  security: [{ bearerAuth: [] }],
  tags: [
    { name: 'Reservations', description: 'Create bookings and track check-in progress.' },
    { name: 'Waivers', description: 'Read waiver signature status and sealed PDFs.' },
    { name: 'Webhooks', description: 'Manage outbound event subscriptions.' },
  ],
  paths: {
    '/reservations': {
      post: {
        tags: ['Reservations'],
        summary: 'Create a reservation',
        description: 'Creates a booking (and a bound session behind it), returning the reservation and its check-in links. Optionally seed attendees and email each a personal check-in link.',
        security: [{ bearerAuth: ['reservations:write'] }],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: '#/components/schemas/ReservationCreate' } } },
        },
        responses: {
          '201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/ReservationCreated' } } } },
          '400': { $ref: '#/components/responses/BadRequest' },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
      get: {
        tags: ['Reservations'],
        summary: 'List reservations',
        description: 'Lists reservations newest-first with signed-vs-expected progress. Cursor-paginated via `created_before` / `next_cursor`.',
        security: [{ bearerAuth: ['reservations:read'] }],
        parameters: [
          { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 50 } },
          { name: 'created_before', in: 'query', description: 'Return reservations created before this ISO timestamp (the previous page\'s next_cursor).', schema: { type: 'string', format: 'date-time' } },
        ],
        responses: {
          '200': { description: 'OK', content: { 'application/json': { schema: { $ref: '#/components/schemas/ReservationList' } } } },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
    },
    '/reservations/{id}': {
      get: {
        tags: ['Reservations'],
        summary: 'Get a reservation',
        description: 'Returns one reservation with its attendees and signed/expected counts. A reservation belonging to another operator returns 404.',
        security: [{ bearerAuth: ['reservations:read'] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'OK', content: { 'application/json': { schema: { $ref: '#/components/schemas/ReservationDetail' } } } },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '404': { $ref: '#/components/responses/NotFound' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
    },
    '/reservations/{id}/members': {
      post: {
        tags: ['Reservations'],
        summary: 'Add attendees',
        description: 'Adds attendees to a reservation, optionally emailing each a personal check-in link. Returns each new member with its check-in URL.',
        security: [{ bearerAuth: ['reservations:write'] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: '#/components/schemas/MembersAdd' } } },
        },
        responses: {
          '201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/MembersAdded' } } } },
          '400': { $ref: '#/components/responses/BadRequest' },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '404': { $ref: '#/components/responses/NotFound' },
          '409': { description: 'Reservation cancelled', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
    },
    '/waivers/{id}': {
      get: {
        tags: ['Waivers'],
        summary: 'Get a waiver',
        description: 'Returns a waiver\'s signature status and, when sealed, a short-lived (5-minute) signed URL to its PDF.',
        security: [{ bearerAuth: ['waivers:read'] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'OK', content: { 'application/json': { schema: { $ref: '#/components/schemas/Waiver' } } } },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '404': { $ref: '#/components/responses/NotFound' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
    },
    '/webhooks': {
      get: {
        tags: ['Webhooks'],
        summary: 'List webhook endpoints',
        security: [{ bearerAuth: ['webhooks:manage'] }],
        responses: {
          '200': { description: 'OK', content: { 'application/json': { schema: { $ref: '#/components/schemas/WebhookList' } } } },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
      post: {
        tags: ['Webhooks'],
        summary: 'Create a webhook endpoint',
        description: 'Registers an HTTPS endpoint for the given events. The signing `secret` is returned once — store it to verify delivery signatures.',
        security: [{ bearerAuth: ['webhooks:manage'] }],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: '#/components/schemas/WebhookCreate' } } },
        },
        responses: {
          '201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/WebhookCreated' } } } },
          '400': { $ref: '#/components/responses/BadRequest' },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
      delete: {
        tags: ['Webhooks'],
        summary: 'Delete a webhook endpoint',
        security: [{ bearerAuth: ['webhooks:manage'] }],
        parameters: [{ name: 'id', in: 'query', required: true, schema: { type: 'string', format: 'uuid' } }],
        responses: {
          '200': { description: 'Deleted', content: { 'application/json': { schema: { type: 'object', properties: { deleted: { type: 'boolean' } } } } } },
          '400': { $ref: '#/components/responses/BadRequest' },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '403': { $ref: '#/components/responses/Forbidden' },
          '404': { $ref: '#/components/responses/NotFound' },
          '429': { $ref: '#/components/responses/RateLimited' },
        },
      },
    },
  },
  components: {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', description: 'A Liabl API key (`liabl_live_…` or `liabl_test_…`).' },
    },
    responses: {
      BadRequest:   { description: 'Invalid request', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      Unauthorized: { description: 'Missing, invalid, revoked, or expired key', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      Forbidden:    { description: 'Key lacks the required scope', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      NotFound:     { description: 'Not found (or not this operator\'s)', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
      RateLimited:  { description: '120 req/min per key exceeded; see Retry-After', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
    },
    schemas: {
      Error: {
        type: 'object',
        properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' } }, required: ['code', 'message'] } },
        required: ['error'],
      },
      MemberInput: {
        type: 'object',
        properties: { full_name: { type: 'string' }, email: { type: 'string', format: 'email' } },
      },
      MemberLink: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          full_name: { type: 'string', nullable: true },
          email: { type: 'string', nullable: true },
          check_in_url: { type: 'string', format: 'uri' },
        },
      },
      ReservationCreate: {
        type: 'object',
        required: ['activity_key'],
        properties: {
          activity_key: { type: 'string', description: 'The operator activity this booking is for.' },
          reservation_date: { type: 'string', format: 'date', description: 'Defaults to today.' },
          party_size: { type: 'integer' },
          organizer_name: { type: 'string' },
          organizer_email: { type: 'string', format: 'email' },
          members: { type: 'array', items: { $ref: '#/components/schemas/MemberInput' } },
          send_invites: { type: 'boolean', description: 'Email each member with an email address a personal check-in link.' },
        },
      },
      ReservationCreated: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          status: { type: 'string' },
          activity_key: { type: 'string' },
          reservation_date: { type: 'string', format: 'date' },
          links: {
            type: 'object',
            properties: {
              self_service: { type: 'string', format: 'uri', description: 'Organizer self-service management link.' },
              shared_check_in: { type: 'string', format: 'uri', description: 'Shared kiosk check-in link.' },
              group_leader: { type: 'string', format: 'uri', description: 'Group-leader one-device signing link.' },
            },
          },
          members: { type: 'array', items: { $ref: '#/components/schemas/MemberLink' } },
        },
      },
      ReservationListItem: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          activity_key: { type: 'string' },
          reservation_date: { type: 'string', format: 'date' },
          status: { type: 'string' },
          party_size: { type: 'integer', nullable: true },
          signed_count: { type: 'integer' },
          expected_count: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
        },
      },
      ReservationList: {
        type: 'object',
        properties: {
          items: { type: 'array', items: { $ref: '#/components/schemas/ReservationListItem' } },
          next_cursor: { type: 'string', format: 'date-time', nullable: true, description: 'Pass as created_before to fetch the next page; null when done.' },
        },
      },
      ReservationMember: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          full_name: { type: 'string', nullable: true },
          email: { type: 'string', nullable: true },
          status: { type: 'string' },
          invited_at: { type: 'string', format: 'date-time', nullable: true },
          waiver_id: { type: 'string', format: 'uuid', nullable: true },
        },
      },
      ReservationDetail: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          status: { type: 'string' },
          activity_key: { type: 'string' },
          reservation_date: { type: 'string', format: 'date' },
          party_size: { type: 'integer', nullable: true },
          organizer_name: { type: 'string', nullable: true },
          organizer_email: { type: 'string', nullable: true },
          signed_count: { type: 'integer' },
          expected_count: { type: 'integer' },
          members: { type: 'array', items: { $ref: '#/components/schemas/ReservationMember' } },
          created_at: { type: 'string', format: 'date-time' },
        },
      },
      MembersAdd: {
        type: 'object',
        required: ['members'],
        properties: {
          members: { type: 'array', minItems: 1, items: { $ref: '#/components/schemas/MemberInput' } },
          send_invites: { type: 'boolean' },
        },
      },
      MembersAdded: {
        type: 'object',
        properties: { members: { type: 'array', items: { $ref: '#/components/schemas/MemberLink' } } },
      },
      Waiver: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          signed: { type: 'boolean' },
          signed_at: { type: 'string', format: 'date-time', nullable: true },
          activity_key: { type: 'string' },
          is_minor: { type: 'boolean' },
          reservation_id: { type: 'string', format: 'uuid', nullable: true },
          reservation_member_id: { type: 'string', format: 'uuid', nullable: true },
          document_hash: { type: 'string', nullable: true },
          pdf_url: { type: 'string', format: 'uri', nullable: true, description: 'Short-lived signed URL; null until sealed.' },
          pdf_url_expires_in: { type: 'integer', nullable: true, description: 'Seconds the pdf_url stays valid.' },
          created_at: { type: 'string', format: 'date-time' },
        },
      },
      WebhookEndpoint: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          url: { type: 'string', format: 'uri' },
          events: { type: 'array', items: { type: 'string' } },
          active: { type: 'boolean' },
          description: { type: 'string', nullable: true },
          last_delivery_at: { type: 'string', format: 'date-time', nullable: true },
          created_at: { type: 'string', format: 'date-time' },
        },
      },
      WebhookList: {
        type: 'object',
        properties: { endpoints: { type: 'array', items: { $ref: '#/components/schemas/WebhookEndpoint' } } },
      },
      WebhookCreate: {
        type: 'object',
        required: ['url', 'events'],
        properties: {
          url: { type: 'string', format: 'uri', description: 'Must be https.' },
          events: {
            type: 'array', minItems: 1,
            items: { type: 'string', enum: ['waiver.signed', 'document.signed', 'reservation.member_signed', 'reservation.completed'] },
          },
          description: { type: 'string' },
        },
      },
      WebhookCreated: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          url: { type: 'string', format: 'uri' },
          events: { type: 'array', items: { type: 'string' } },
          secret: { type: 'string', description: 'HMAC signing secret — shown once, store it now.' },
        },
      },
    },
  },
} as const
