'use client'
import { useState, useEffect } from 'react'
import { ParticipantAnswers } from '@/lib/document-engine'
import { IconVerified } from '@liabl/ui'
import { fetchPaymentQuote, createPaymentIntent, formatMoney } from '@/lib/payments-client'
import PaymentPanel from '@/components/participant/PaymentPanel'

interface Props {
  answers: ParticipantAnswers
  labels: Record<string, string>
  onRestart: () => void
  restartLabel?: string
  waiverId?: string | null   // S2b: enables the optional Pay step when set
  accent?: string
}

export default function StepConfirm({ answers, labels, onRestart, restartLabel, waiverId, accent }: Props) {
  const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  const firstName = answers.fullName?.split(' ')[0] ?? 'there'

  return (
    <div className="card text-center">
      <div className="w-16 h-16 rounded-full bg-success-light flex items-center justify-center mx-auto mb-4">
        <IconVerified size={32} color="#15803D"/>
      </div>
      <h2 className="font-serif text-2xl mb-2" style={{letterSpacing:'-0.01em'}}>You&apos;re all set, {firstName}.</h2>
      <p className="text-gray-500 text-sm mb-6">Your signed waiver has been recorded and emailed to <span className="text-ink font-medium">{answers.email}</span>.</p>
      <div className="flex flex-wrap gap-2 justify-center mb-6">
        {[`Signed at ${time}`,labels[answers.activityKey]??'Activity','ESIGN compliant','LIABL Pass ✦'].map(tag=>(
          <span key={tag} className="bg-surface border border-black/10 text-xs px-3 py-1.5 rounded-full text-gray-500">{tag}</span>
        ))}
      </div>

      {waiverId && <PaySection waiverId={waiverId} accent={accent} />}

      <p className="text-xs text-gray-400 mb-6 max-w-sm mx-auto leading-relaxed">
        Generated by <span className="text-brand font-medium">LIABL Document Intelligence</span> — adaptive, activity-specific, and legally defensible from the first signature.
      </p>
      <button onClick={onRestart} className="btn-primary max-w-xs mx-auto">{restartLabel ?? 'Demo again'}</button>
    </div>
  )
}

function PaySection({ waiverId, accent }: { waiverId: string; accent?: string }) {
  const [amount, setAmount] = useState<{ cents: number; currency: string } | null>(null)
  const [secret, setSecret] = useState<string | null>(null)
  const [starting, setStarting] = useState(false)
  const [paid, setPaid] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let live = true
    fetchPaymentQuote(waiverId).then(q => {
      if (live && q.payable && q.amountCents) setAmount({ cents: q.amountCents, currency: q.currency || 'usd' })
    })
    return () => { live = false }
  }, [waiverId])

  async function start() {
    setStarting(true); setError(null)
    try {
      const r = await createPaymentIntent(waiverId)
      if (r.clientSecret && r.amountCents) {
        setSecret(r.clientSecret)
        setAmount({ cents: r.amountCents, currency: r.currency || 'usd' })
      } else {
        setError('Payment is unavailable right now.')
      }
    } catch {
      setError('Could not start payment.')
    } finally { setStarting(false) }
  }

  if (!amount) return null

  if (paid) {
    return (
      <div className="mb-6 rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700">
        Payment of {formatMoney(amount.cents, amount.currency)} received — thank you!
      </div>
    )
  }

  return (
    <div className="mb-6 rounded-xl border border-black/10 p-4 text-left max-w-sm mx-auto">
      <div className="flex items-center justify-between mb-3">
        <span className="text-sm font-medium text-ink">Amount due</span>
        <span className="text-lg font-semibold text-ink">{formatMoney(amount.cents, amount.currency)}</span>
      </div>
      {error && <div className="mb-3 text-sm text-red-600">{error}</div>}
      {secret ? (
        <PaymentPanel clientSecret={secret} amountCents={amount.cents} currency={amount.currency} accent={accent} onPaid={() => setPaid(true)} />
      ) : (
        <button onClick={start} disabled={starting} className="btn-primary text-sm w-full">
          {starting ? 'Loading…' : `Pay ${formatMoney(amount.cents, amount.currency)}`}
        </button>
      )}
      <p className="text-[11px] text-gray-400 mt-2 text-center">Secured by Stripe. Optional — you can pay at the counter instead.</p>
    </div>
  )
}
