import { ParticipantAnswers, ACTIVITY_LABELS } from '@/lib/document-engine'
import { IconVerified } from '@/components/icons'
interface Props { answers:ParticipantAnswers; onRestart:()=>void }
export default function StepConfirm({ answers, onRestart }: Props) {
  const time=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})
  const firstName=answers.fullName?.split(' ')[0]??'there'
  return (
    <div className="card text-center">
      <div className="w-16 h-16 rounded-full bg-success-light flex items-center justify-center mx-auto mb-4">
        <IconVerified size={32} color="#15803D"/>
      </div>
      <h2 className="font-serif text-2xl mb-2" style={{letterSpacing:'-0.01em'}}>You&apos;re all set, {firstName}.</h2>
      <p className="text-gray-500 text-sm mb-6">Your signed waiver has been recorded and emailed to <span className="text-ink font-medium">{answers.email}</span>.</p>
      <div className="flex flex-wrap gap-2 justify-center mb-6">
        {[`Signed at ${time}`,ACTIVITY_LABELS[answers.activityKey]??'Activity','ESIGN compliant','LIABL Pass ✦'].map(tag=>(
          <span key={tag} className="bg-surface border border-black/10 text-xs px-3 py-1.5 rounded-full text-gray-500">{tag}</span>
        ))}
      </div>
      <p className="text-xs text-gray-400 mb-6 max-w-sm mx-auto leading-relaxed">
        Generated by <span className="text-brand font-medium">LIABL Document Intelligence</span> — adaptive, activity-specific, and legally defensible from the first signature.
      </p>
      <button onClick={onRestart} className="btn-primary max-w-xs mx-auto">Demo again</button>
    </div>
  )
}
